#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: ./plotVSthreads_1schedq </path/to/data/file> "
else
    filenameEXT=$(basename "$1")
    title=$(echo "$filenameEXT" | sed 's/.*-\(.*\)$/\1/g')
    filename=$(echo "$filenameEXT" | sed 's/\(.*\).txt$/\1/g') 

    # write gnuplot.gpi file for 4thread 
    echo "set term pngcairo dashed" > "$filename.gpi"
    echo "set output \"$filename.png\"" >> "$filename.gpi"
    echo "set key right top" >> "$filename.gpi"
    echo "set style line 1 lt 1 lc rgb \"red\" lw 1" >> "$filename.gpi"
    echo "set style line 2 lt 2 lc rgb \"orange\" lw 1" >> "$filename.gpi"
    echo "set style line 3 lt 3 lc rgb \"green\" lw 1" >> "$filename.gpi"
    echo "set style line 4 lt 4 lc rgb \"cyan\" lw 1" >> "$filename.gpi"
    echo "set style line 5 lt 5 lc rgb \"blue\" lw 1" >> "$filename.gpi"
    echo "set style line 6 lt 6 lc rgb \"violet\" lw 1" >> "$filename.gpi"
    echo "set style line 7 lt 7 lc rgb \"black\" lw 1" >> "$filename.gpi"
    echo "set xlabel 'Number of LTSF Queues'" >> "$filename.gpi"
    echo "set ylabel 'Simulation Time (s)'" >> "$filename.gpi"
#1 thread
    echo "plot \"<(sed -n '4,4p' $1)\" using 1:2:3 title '1 Worker Thread' with lines ls 1, \\" >> "$filename.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 1, \\" >> "$filename.gpi"
#2 threads
    echo "\"<(sed -n '7,9p' $1)\" using 1:2:3 title '2 Worker Threads' with lines ls 2, \\" >> "$filename.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 2, \\" >> "$filename.gpi"
#3 threads
    echo "\"<(sed -n '11,14p' $1)\" using 1:2:3 title '3 Worker Threads' with lines ls 3, \\" >> "$filename.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 3, \\" >> "$filename.gpi"
#4 threads
    echo "\"<(sed -n '16,20p' $1)\" using 1:2:3 title '4 Worker Threads' with lines ls 4, \\" >> "$filename.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 4, \\" >> "$filename.gpi"
#5 threads
    echo "\"<(sed -n '22,27p' $1)\" using 1:2:3 title '5 Worker Threads' with lines ls 5, \\" >> "$filename.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 5, \\" >> "$filename.gpi"
#6 threads
    echo "\"<(sed -n '29,35p' $1)\" using 1:2:3 title '6 Worker Threads' with lines ls 6, \\" >> "$filename.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 6, \\" >> "$filename.gpi"
#7 threads
    echo "\"<(sed -n '37,43p' $1)\" using 1:2:3 title '7 Worker Threads' with lines ls 7, \\" >> "$filename.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 7" >> "$filename.gpi"

    # perform actual plotting
    gnuplot "$filename.gpi"

    rm *.gpi
    mv *.png ../figures/
fi 
