#!/bin/bash

./plotDSC_VSschedq_Xthreads_std ../data/hugeepidemicsim-NOmig-timeVSschedQs-multiset.txt ../data/hugeepidemicsim-NOmig-timeVSschedQs-splaytree.txt static std 

./plotDSC_VSschedq_Xthreads_std ../data/hugeepidemicsim-NOmig-timeVSschedQs-multiset.txt ../data/hugeepidemicsim-NOmig-timeVSschedQs-splaytree.txt static hle 

./plotDSC_VSschedq_Xthreads_std ../data/hugeepidemicsim-NOmig-timeVSschedQs-multiset.txt ../data/hugeepidemicsim-NOmig-timeVSschedQs-splaytree.txt static rtm-1retry 

./plotDSC_VSschedq_Xthreads_std ../data/hugeepidemicsim-NOmig-timeVSschedQs-multiset.txt ../data/hugeepidemicsim-NOmig-timeVSschedQs-splaytree.txt static rtm-9retry

./plotDSC_VSschedq_Xthreads_std ../data/hugeepidemicsim-NOmig-timeVSschedQs-multiset.txt ../data/hugeepidemicsim-NOmig-timeVSschedQs-splaytree.txt static rtm-19retry

./plotVSschedq_Xthreads_separatePlots ../data/hugeepidemicsim-NOmig-timeVSschedQs-multiset.txt static

./plotVSschedq_Xthreads_separatePlots ../data/hugeepidemicsim-CONTmig-timeVSschedQs-multiset.txt dynamic 

./plotVSschedq_Xthreads_separatePlots ../data/hugeepidemicsim-XEVENTmig-timeVSschedQs-multiset.txt static

./plotVSthreads_1schedq ../data/hugeepidemicsim-NOmig-timeVSthreads-multiset.txt

