#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: ./plotVSthreads_1schedq </path/to/data/file> "
else
    filenameEXT=$(basename "$1")
    title=$(echo "$filenameEXT" | sed 's/.*-\(.*\)$/\1/g')
    filename=$(echo "$filenameEXT" | sed 's/\(.*\).txt$/\1/g') 

    schq1_lower=4
    schq1_upper=11
    
    # write gnuplot.gpi file for 1schQ 
    echo "set terminal pdf" > "$filename-1schQ.gpi"
    echo "set output \"$filename-1schQ.pdf\"" >> "$filename-1schQ.gpi"
    echo "set key right top" >> "$filename-1schQ.gpi"
    echo "set xrange [1:7]" >> "$filename-1schQ.gpi"
    echo "set style line 1 lt 1 lc rgb \"black\" lw 1" >> "$filename-1schQ.gpi"
    echo "set style line 2 lt 2 lc rgb \"red\" lw 1" >> "$filename-1schQ.gpi"
    echo "set style line 3 lt 3 lc rgb \"orange\" lw 1" >> "$filename-1schQ.gpi"
    echo "set style line 4 lt 4 lc rgb \"green\" lw 1" >> "$filename-1schQ.gpi"
    echo "set style line 5 lt 5 lc rgb \"blue\" lw 1" >> "$filename-1schQ.gpi"
    echo "set xlabel 'Number of Worker Threads'" >> "$filename-1schQ.gpi"
    echo "set ylabel 'Simulation Time (s)'" >> "$filename-1schQ.gpi"
    echo "plot \"<(sed -n '$schq1_lower,${schq1_upper}p' $1)\" using 1:2:3 title 'std' with lines ls 1, \\" >> "$filename-1schQ.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 1, \\" >> "$filename-1schQ.gpi"
    echo "'' using 1:4:5 title 'hle' with lines ls 2, \\" >> "$filename-1schQ.gpi"
    echo "'' using 1:4:5 notitle with yerrorbars ls 2, \\">> "$filename-1schQ.gpi"
    echo "'' using 1:6:7 title 'rtm-1retry' with lines ls 3, \\" >> "$filename-1schQ.gpi"
    echo "'' using 1:6:7 notitle with yerrorbars ls 3, \\" >> "$filename-1schQ.gpi"
    echo "'' using 1:8:9 title 'rtm-4retry' with lines ls 4, \\" >> "$filename-1schQ.gpi"
    echo "'' using 1:8:9 notitle with yerrorbars ls 4, \\" >> "$filename-1schQ.gpi"
    echo "'' using 1:10:11 title 'rtm-9retry' with lines ls 5, \\" >> "$filename-1schQ.gpi"
    echo "'' using 1:10:11 notitle with yerrorbars ls 5 " >> "$filename-1schQ.gpi"

    # perform actual plotting
    gnuplot "$filename-1schQ.gpi"

    rm *.gpi
    mv *.pdf ../figures/
fi
