#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: ./plotTRXsize </path/to/data/file>"
else
    filenameEXT=$(basename "$1")
    title=$(echo "$filenameEXT" | sed 's/.*-\(.*\)$/\1/g')
    filename=$(echo "$filenameEXT" | sed 's/\(.*\).txt$/\1/g')

    # write gnuplot.gpi file for 1schQ 
    echo "set term pngcairo dashed" > "$filename.gpi"
    echo "set output \"$filename.png\"" >> "$filename.gpi"
    echo "set key left top" >> "$filename.gpi"
    echo "set logscale x" >> "$filename.gpi"
    echo "set xrange [1000:1000000]" >> "$filename.gpi"
    echo "set style line 1 lt 1 lc 1 lw 1" >> "$filename.gpi"
    echo "set xlabel 'Number of Write Operations'" >> "$filename.gpi"
    echo "set ylabel 'Abort Rate'" >> "$filename.gpi"
    echo "plot \"<(sed -n '19,47p' $1)\" using 1:2 notitle with lp ls 1" >> "$filename.gpi"

    # perform actual plotting
    gnuplot "$filename.gpi"

    rm *.gpi
    mv *.png ../figures/
fi
