#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: ./plotTRXsize </path/to/data/file>"
else
    filenameEXT=$(basename "$1")
    title=$(echo "$filenameEXT" | sed 's/.*-\(.*\)$/\1/g')
    filename=$(echo "$filenameEXT" | sed 's/\(.*\).txt$/\1/g')

    # write gnuplot.gpi file for 1schQ 
    echo "set terminal pdf" > "$filename.gpi"
    echo "set output \"$filename.pdf\"" >> "$filename.gpi"
    echo "set key left top" >> "$filename.gpi"
    echo "set logscale x 2" >> "$filename.gpi"
    echo "set style line 1 lt 1 lc 1 lw 1" >> "$filename.gpi"
    echo "set style line 2 lt 1 lc 3 lw 1" >> "$filename.gpi"
    echo "set xlabel 'Number of Cache Lines Accessed'" >> "$filename.gpi"
    echo "set ylabel 'Abort Rate'" >> "$filename.gpi"
    echo "plot \"<(sed -n '2,19p' $1)\" using 1:2 title 'write-set' with lp ls 1, \\" >> "$filename.gpi"
    echo "\"<(sed -n '20,37p' $1)\" using 1:2 title 'read-set' with lp ls 2" >> "$filename.gpi"

    # perform actual plotting
    gnuplot "$filename.gpi"

    rm *.gpi
    mv *.pdf ../figures/
fi
