#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: ./plotVSthreads_1schedq </path/to/data/file> "
else
    filename=$(basename "$1")
    title=$(echo "$filename" | sed 's/.*-\(.*\)$/\1/g')

    # write gnuplot.gpi file for 4thread 
    echo "set term pngcairo dashed" > "$1-4thread.gpi"
    echo "set output \"$1-4thread.png\"" >> "$1-4thread.gpi"
    echo "set key right top" >> "$1-4thread.gpi"
    echo "set xrange [1:4]" >> "$1-4thread.gpi"
    echo "set style line 1 lt 1 lc rgb \"black\" lw 1" >> "$1-4thread.gpi"
    echo "set style line 2 lt 2 lc rgb \"red\" lw 1" >> "$1-4thread.gpi"
    echo "set style line 3 lt 3 lc rgb \"orange\" lw 1" >> "$1-4thread.gpi"
    echo "set style line 4 lt 4 lc rgb \"green\" lw 1" >> "$1-4thread.gpi"
    echo "set style line 5 lt 5 lc rgb \"blue\" lw 1" >> "$1-4thread.gpi"
    echo "set xlabel 'Number of LTSF Queues'" >> "$1-4thread.gpi"
    echo "set ylabel 'Simulation Time (s)'" >> "$1-4thread.gpi"
    echo "plot \"<(sed -n '16,20p' $1)\" using 1:2:3 title 'std' with lines ls 1, \\" >> "$1-4thread.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 1, \\" >> "$1-4thread.gpi"
    echo "'' using 1:4:5 title 'hle' with lines ls 2, \\" >> "$1-4thread.gpi"
    echo "'' using 1:4:5 notitle with yerrorbars ls 2, \\">> "$1-4thread.gpi"
    echo "'' using 1:6:7 title 'rtm-1retry' with lines ls 3, \\" >> "$1-4thread.gpi"
    echo "'' using 1:6:7 notitle with yerrorbars ls 3, \\" >> "$1-4thread.gpi"
    echo "'' using 1:8:9 title 'rtm-4retry' with lines ls 4, \\" >> "$1-4thread.gpi"
    echo "'' using 1:8:9 notitle with yerrorbars ls 4, \\" >> "$1-4thread.gpi"
    echo "'' using 1:10:11 title 'rtm-9retry' with lines ls 5, \\" >> "$1-4thread.gpi"
    echo "'' using 1:10:11 notitle with yerrorbars ls 5 " >> "$1-4thread.gpi"

    # perform actual plotting
    gnuplot "$1-4thread.gpi"

    echo "set term pngcairo dashed" > "$1-5thread.gpi"
    echo "set output \"$1-5thread.png\"" >> "$1-5thread.gpi"
    echo "set key right top" >> "$1-5thread.gpi"
    echo "set xrange [1:5]" >> "$1-5thread.gpi"
    echo "set style line 1 lt 1 lc rgb \"black\" lw 1" >> "$1-5thread.gpi"
    echo "set style line 2 lt 2 lc rgb \"red\" lw 1" >> "$1-5thread.gpi"
    echo "set style line 3 lt 3 lc rgb \"orange\" lw 1" >> "$1-5thread.gpi"
    echo "set style line 4 lt 4 lc rgb \"green\" lw 1" >> "$1-5thread.gpi"
    echo "set style line 5 lt 5 lc rgb \"blue\" lw 1" >> "$1-5thread.gpi"
    echo "set xlabel 'Number of LTSF Queues'" >> "$1-5thread.gpi"
    echo "set ylabel 'Simulation Time (s)'" >> "$1-5thread.gpi"
    echo "plot \"<(sed -n '22,27p' $1)\" using 1:2:3 title 'std' with lines ls 1, \\" >> "$1-5thread.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 1, \\" >> "$1-5thread.gpi"
    echo "'' using 1:4:5 title 'hle' with lines ls 2, \\" >> "$1-5thread.gpi"
    echo "'' using 1:4:5 notitle with yerrorbars ls 2, \\">> "$1-5thread.gpi"
    echo "'' using 1:6:7 title 'rtm-1retry' with lines ls 3, \\" >> "$1-5thread.gpi"
    echo "'' using 1:6:7 notitle with yerrorbars ls 3, \\" >> "$1-5thread.gpi"
    echo "'' using 1:8:9 title 'rtm-4retry' with lines ls 4, \\" >> "$1-5thread.gpi"
    echo "'' using 1:8:9 notitle with yerrorbars ls 4, \\" >> "$1-5thread.gpi"
    echo "'' using 1:10:11 title 'rtm-9retry' with lines ls 5, \\" >> "$1-5thread.gpi"
    echo "'' using 1:10:11 notitle with yerrorbars ls 5 " >> "$1-5thread.gpi"

    # perform actual plotting
    gnuplot "$1-5thread.gpi"

    echo "set term pngcairo dashed" > "$1-6thread.gpi"
    echo "set output \"$1-6thread.png\"" >> "$1-6thread.gpi"
    echo "set key right top" >> "$1-6thread.gpi"
    echo "set xrange [1:6]" >> "$1-6thread.gpi"
    echo "set style line 1 lt 1 lc rgb \"black\" lw 1" >> "$1-6thread.gpi"
    echo "set style line 2 lt 2 lc rgb \"red\" lw 1" >> "$1-6thread.gpi"
    echo "set style line 3 lt 3 lc rgb \"orange\" lw 1" >> "$1-6thread.gpi"
    echo "set style line 4 lt 4 lc rgb \"green\" lw 1" >> "$1-6thread.gpi"
    echo "set style line 5 lt 5 lc rgb \"blue\" lw 1" >> "$1-6thread.gpi"
    echo "set xlabel 'Number of LTSF Queues'" >> "$1-6thread.gpi"
    echo "set ylabel 'Simulation Time (s)'" >> "$1-6thread.gpi"
    echo "plot \"<(sed -n '29,35p' $1)\" using 1:2:3 title 'std' with lines ls 1, \\" >> "$1-6thread.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 1, \\" >> "$1-6thread.gpi"
    echo "'' using 1:4:5 title 'hle' with lines ls 2, \\" >> "$1-6thread.gpi"
    echo "'' using 1:4:5 notitle with yerrorbars ls 2, \\">> "$1-6thread.gpi"
    echo "'' using 1:6:7 title 'rtm-1retry' with lines ls 3, \\" >> "$1-6thread.gpi"
    echo "'' using 1:6:7 notitle with yerrorbars ls 3, \\" >> "$1-6thread.gpi"
    echo "'' using 1:8:9 title 'rtm-4retry' with lines ls 4, \\" >> "$1-6thread.gpi"
    echo "'' using 1:8:9 notitle with yerrorbars ls 4, \\" >> "$1-6thread.gpi"
    echo "'' using 1:10:11 title 'rtm-9retry' with lines ls 5, \\" >> "$1-6thread.gpi"
    echo "'' using 1:10:11 notitle with yerrorbars ls 5 " >> "$1-6thread.gpi"

    # perform actual plotting
    gnuplot "$1-6thread.gpi"

    echo "set term pngcairo dashed" > "$1-7thread.gpi"
    echo "set output \"$1-7thread.png\"" >> "$1-7thread.gpi"
    echo "set key right top" >> "$1-7thread.gpi"
    echo "set xrange [1:11]" >> "$1-7thread.gpi"
    echo "set style line 1 lt 1 lc rgb \"black\" lw 1" >> "$1-7thread.gpi"
    echo "set style line 2 lt 2 lc rgb \"red\" lw 1" >> "$1-7thread.gpi"
    echo "set style line 3 lt 3 lc rgb \"orange\" lw 1" >> "$1-7thread.gpi"
    echo "set style line 4 lt 4 lc rgb \"green\" lw 1" >> "$1-7thread.gpi"
    echo "set style line 5 lt 5 lc rgb \"blue\" lw 1" >> "$1-7thread.gpi"
    echo "set xlabel 'Number of LTSF Queues'" >> "$1-7thread.gpi"
    echo "set ylabel 'Simulation Time (s)'" >> "$1-7thread.gpi"
    echo "plot \"<(sed -n '37,48p' $1)\" using 1:2:3 title 'std' with lines ls 1, \\" >> "$1-7thread.gpi"
    echo "'' using 1:2:3 notitle with yerrorbars ls 1, \\" >> "$1-7thread.gpi"
    echo "'' using 1:4:5 title 'hle' with lines ls 2, \\" >> "$1-7thread.gpi"
    echo "'' using 1:4:5 notitle with yerrorbars ls 2, \\">> "$1-7thread.gpi"
    echo "'' using 1:6:7 title 'rtm-1retry' with lines ls 3, \\" >> "$1-7thread.gpi"
    echo "'' using 1:6:7 notitle with yerrorbars ls 3, \\" >> "$1-7thread.gpi"
    echo "'' using 1:8:9 title 'rtm-4retry' with lines ls 4, \\" >> "$1-7thread.gpi"
    echo "'' using 1:8:9 notitle with yerrorbars ls 4, \\" >> "$1-7thread.gpi"
    echo "'' using 1:10:11 title 'rtm-9retry' with lines ls 5, \\" >> "$1-7thread.gpi"
    echo "'' using 1:10:11 notitle with yerrorbars ls 5 " >> "$1-7thread.gpi"

    # perform actual plotting
    gnuplot "$1-7thread.gpi"


fi
